name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy=1.12
  - scipy=0.19
  - matplotlib=2.0
  - h5py=2.7
  - ipykernel=4.8
  - jupyter=1.0
  - notebook=5.7
  - decorator=4.1
  - pip