name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy=1.16
  - scipy=1.2
  - matplotlib=2.2
  - h5py=2.10
  - ipykernel=4
  - notebook=5
  - jupyter=1
  - decorator=4.1
  - pip